"""move pinned column to Membership model

Revision ID: 18ac236c8afa
Revises: c9c5a263e54b
Create Date: 2025-11-01 09:16:23.692285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18ac236c8afa'
down_revision: Union[str, Sequence[str], None] = 'c9c5a263e54b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_memberships', sa.Column('pinned', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_chat_memberships_pinned'), 'chat_memberships', ['pinned'], unique=False)
    op.drop_index(op.f('ix_chats_pinned'), table_name='chats')
    op.drop_column('chats', 'pinned')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('pinned', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_chats_pinned'), 'chats', ['pinned'], unique=False)
    op.drop_index(op.f('ix_chat_memberships_pinned'), table_name='chat_memberships')
    op.drop_column('chat_memberships', 'pinned')
    # ### end Alembic commands ###
