"""add pinned colum to Chat model

Revision ID: 25f237ff3037
Revises: 6edc81589ed5
Create Date: 2025-10-31 09:13:14.018794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25f237ff3037'
down_revision: Union[str, Sequence[str], None] = '6edc81589ed5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('pinned', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_chats_pinned'), 'chats', ['pinned'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chats_pinned'), table_name='chats')
    op.drop_column('chats', 'pinned')
    # ### end Alembic commands ###
