"""add invite_code column to Chat model

Revision ID: 682eb5e19ff2
Revises: c4de6224c78d
Create Date: 2025-11-07 11:30:59.938176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '682eb5e19ff2'
down_revision: Union[str, Sequence[str], None] = 'c4de6224c78d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('invite_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'invite_code')
    # ### end Alembic commands ###
