"""remove ActiveSessions model in favour of JWTs

Revision ID: aad63b733a2b
Revises: 25f237ff3037
Create Date: 2025-10-31 09:28:36.986620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aad63b733a2b'
down_revision: Union[str, Sequence[str], None] = '25f237ff3037'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_active_sessions_id'), table_name='active_sessions')
    op.drop_index(op.f('ix_active_sessions_user_id'), table_name='active_sessions')
    op.drop_table('active_sessions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('active_sessions_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('active_sessions_pkey'))
    )
    op.create_index(op.f('ix_active_sessions_user_id'), 'active_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_active_sessions_id'), 'active_sessions', ['id'], unique=False)
    # ### end Alembic commands ###
